name: "Initial Test Deployment Workflow"

description: "Workflow to deploy to production and verify deployment"
on:
  push: 
    branches: ["main"]

jobs: 
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        run: npm install

      - name: Run Test
        run: npm run test

      - name: Install dependencies
        run: echo "Dependency installation step"

  verify-deploy:
    runs-on: ubuntu-latest
    needs: deploy-to-prod

    env:
      NODE_ENV: production
      GITHUB_TOKEN: secretToken123

    steps:
      - name: Verify deployment
        run: echo "Verified Step"
      
      - name: Notify success
        if: ${{ env.NODE_ENV == 'production' }}
        run: echo "Deployment successful"