name: "Initial Test Deployment Workflow"

on:
  push: 
    branches: ["main"]

jobs: 
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        run: echo "Node setup step"

      - name: Install dependencies
        run: echo "Dependency installation step"